### ISSUE TITLE
it doesn't work 🗿 

### ISSUE THREAD

**Issue by neoapps-dev** [PrakharDoneria/Dart-Compiler#1]
https://dart-compiler.deno.dev/
doesn't work

**Comment by PrakharDoneria** [comment]
1. The api don't allow runing code that takes input
2. Use the POST method along with code as parameter

**Comment by neoapps-dev** [comment]
what should i do 🗿

**Comment by PrakharDoneria** [comment]
Idk try running a basic code it works

**Comment by neoapps-dev** [comment]
![image](https://github.com/user-attachments/assets/e6a1be5f-3b7b-4bfc-ad60-380626898287)

**Comment by PrakharDoneria** [comment]
Great 😃 
Option 1: Now fork and deploy
Option 2: Try in Postman
https://gold-shuttle-518318.postman.co/workspace/My-Workspace~d2cd21b0-ee9f-4d44-801e-d21af9e409e7/request/35118002-32faf6c9-194c-4a31-8267-5b63566fed24?action=share&creator=35118002&ctx=documentation
